import React, { useState, useEffect } from "react"
import Layout from "@/components/Dashboard/Layout"
import TopCards from "../components/Dashboard/TopCards"
import BarChart from "../components/Dashboard/BarChart"
import { EditAdminForm } from "@/components/Dashboard/EditAdminForm"
// import RecentOrders from "../components/Dashboard/RecentOrders";
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

function Account() {
  const [user, setUser] = useState([])

  const fetchUser = async () => {
    
    try {
      const res = await fetch(`http://127.0.0.1:8000/api/showAdmin`, {
        method: "GET",
        headers: {
          Authorization: `Bearer ${localStorage.getItem('token')}`,
          "Content-Type": "application/json",
          "Accept": "application/json",
        },
      })

      if (!res.ok) {
        throw new Error("Réponse de l'API non valide")
      }

      const json = await res.json()
      setUser(json)
    } catch (error) {
      console.error("Une erreur s'est produite :", error)
    }
  }

  useEffect(() => {
    fetchUser()
  }, [])

  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-purple-50 min-h-screen">
        <Layout>
          <div className="flex ">
            <div className="lg:cols-span-3 md:col-span-4 bg-white rounded-lg shadow-lg p-6 mt-10 flex">
              <div className="mb-2 pl- text-center pr-100 ">
                <Image
                  src="/images/adminProfile.jpg"
                  alt="User Profile"
                  width={200}
                  height={200}
                />
              </div>
              <h1 className="text-2xl font-bold text-gray-800 mt-10 ">
                Admin Information
              </h1>
              <br></br>
              <hr className="my-4" />{" "}
              
                <>
                  {" "}
                  <p className="text-gray-600 p-3 mt-10">
                    {" "}
                    <span className="font-bold">First Name: </span>{" "}
                    {user.first_name}
                  </p>
                  <p className="text-gray-600 p-3 mt-10">
                    <span className="font-bold">Last Name: </span>
                    {user.last_name}
                  </p>
                  <p className="text-gray-600 p-3 mt-10">
                    <span className="font-bold">E-mail: </span> {user.email}
                  </p>
                  <p className="text-gray-600 p-3 mt-10">
                    <span className="font-bold">Phone: </span> {user.phone}
                  </p>
                </>
             
            </div>
          </div>
          <div className="p-6 mt-4 mb-4 bg-white rounded-lg shadow-xl min-h-screen">
            <h2 className="text-2xl font-bold text-gray-800 mt-4 p-4">Edit your infos</h2>
            <EditAdminForm/>
          </div>
        </Layout>
      </main>  
    </>
  )
}

export default Account
