import React from "react"
import Layout from "@/components/Dashboard/Layout"
import TopCards from "../components/Dashboard/TopCards"
import BarChart from "../components/Dashboard/BarChart"
// import RecentOrders from "../components/Dashboard/RecentOrders";
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

function Account() {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white min-h-screen">
        <Layout>
          <div className="justify-center">
            <div className="mb-4 pl- text-center pr-100 ">
              <Image
                src="/images/adminProfile.jpg"
                alt="User Profile"
                width={200}
                height={200}
              />
            </div>
            <div className="lg:cols-span-3 md:col-span-4 bg-gray-100 rounded-lg shadow-lg p-6">
              <h1 className="text-2xl font-bold text-gray-800">
                Admin Profile
              </h1>
              <hr className="my-4" />
              <p className="text-gray-600 p-3">First Name : Meriem</p>
              <p className="text-gray-600 p-3">Last Name : MANSOURI</p>
              <p className="text-gray-600 p-3">Email : meriem.mansouri@gmail.com</p>
            
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}

export default Account


